# Generated by Django 4.1.5 on 2023-01-15 14:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(error_messages={'unique': 'A user with that login already exists.'}, max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
